### ISSUE TITLE
训练15轮后忽然数组报错？

### ISSUE THREAD

**Issue by aniseanise** [fc-123/Semantic-segmentation#2]
`Traceback (most recent call last):
  File "/root/autodl-tmp/train.py", line 105, in <module>
    main()
  File "/root/autodl-tmp/train.py", line 62, in main
    train_class_acc = train_class_acc + eval_metrix['class_accuracy']
ValueError: operands could not be broadcast together with shapes (32,) (31,) `

**Comment by aniseanise** [comment]
![1](https://github.com/fc-123/Semantic-segmentation/assets/99158486/1337b8e5-22ef-49cf-8a72-98d2ac87beda)
